config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

  resources :profiles

  resources :posts do
    member do
      post 'upvote'
    end
  end

  resources :votes

  resources :images
   get 'imgur', to: 'images#imgur'

  root 'welcome#index'
  get '/about', to: 'welcome#about'

  delete 'users/:id/delete' => 'users#destroy'

  get '/all' => 'posts#all'

  get '/archive' => 'archive#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user

  has_attached_file :avatar, :styles =>
  { :medium => "300x300>", :thumb => "100x100>" },
  :default_url => "missing.png", id: "avatar"
  validates_attachment_content_type :avatar,
  content_type: /\Aimage\/.*\Z/

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile = Profile.new
  end

  def show
    @profile = Profile.where(user_id: params[:id]).first
    @posts = Post.where(user_id: params[:id])
  end

  def edit
    @profile = get_profile
  end

  def create
    @profile = Profile.create(profile_params)
    current_user.profile = @profile
    redirect_to profile_path(current_user)
  end

  def update
    user = current_user
    if user.profile.update(profile_params)
      redirect_to profile_path(current_user), notice: "Profile updated."
    else
      render :new, alert: "There was a problem."
    end
  end

  private

  def get_profile
    current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:fname, :lname, :location, :avatar, :username).merge(user_id: current_user.id)
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div id="edit-profile-wrapper">

<div id="nav">
<%= link_to image_tag("logo-2.png", :class => "nav-home"), root_path %><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-logout" %>
</div>

<div id="profile-forms">
   <h2>Edit Your Profile</h2>
   <%= form_for @profile, :html => { :multipart => true } do |f| %>
   <%= f.label :username, "Username" %>
   <%= f.text_field :username %><br>
   <%= f.label :fname, "First Name" %>
   <%= f.text_field :fname %><br>
   <%= f.label :lname, "Last Name" %>
   <%= f.text_field :lname %><br>
   <%= f.label :location, "Location" %>
   <%= f.text_field :location %><br>
   <%= f.label :avatar, "Profile Photo" %>
   <%= f.file_field :avatar %><br><br>
   <%= f.submit :update, :class => "form-button" %>
   <% end %>
</div>

app/views/profiles/new.html.erb
<div id="new-profile-wrapper">

   <div id="nav">
      <%= link_to image_tag("logo-2.png", :class => "nav-home"), root_path %>
      <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-logout" %>
      <% end %>
   </div>

   <div id="profile-forms">
      <h2>Create Your Profile</h2>
      <h3>You must set up a profile to post.</h3>
      <%= form_for @profile, :html => { :multipart => true } do |f| %>
      <%= f.label :username, "Username" %>
      <%= f.text_field :username %><br>
      <%= f.label :fname, "First Name" %>
      <%= f.text_field :fname %><br>
      <%= f.label :lname, "Last Name" %>
      <%= f.text_field :lname %><br>
      <%= f.label :location, "Location" %>
      <%= f.text_field :location %><br>
      <%= f.label :avatar, "Profile Photo" %>
      <%= f.file_field :avatar %><br><br>
      <%= f.submit :create, :class => "form-button" %>
      <% end %>
   </div>

</div>

app/views/profiles/show.html.erb
<div id="profile-wrapper">
  <div id="nav">
    <%= link_to image_tag("logo-2.png", :class => "nav-home"), root_path %><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-logout" %>
  </div>
  <div id="profile-info">
    <h2><%= @profile.fname %>'s Profile</h2>
    <%= image_tag @profile.avatar.url, :id => "avatar" %>
    <h3>Name: <%= @profile.fname %> <%= @profile.lname %></h3><br>
    <h3>Location: <%= @profile.location %> </h3><br>
    <% if current_user && current_user.id == @profile.user_id %>
    <%= button_to 'Edit Profile', edit_profile_path(current_user), method: :get, :class => "form-button" %>
    <%= button_to "Cancel My Account", "/users/#{current_user.id}/delete", method: :delete, :class => "form-button2" %>
    <% end %>
    <h2><%=@profile.fname%>'s Wall of Memes</h2>
    <div id="meme-container">
      <% @posts.reverse.each do |p|  %>
      <%= link_to image_tag(p.avatar.url), post_path(p.id), :id => "avatar-meme" %>
      <% end %>
    </div>
  </div>
</div>