config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

  resources :profiles

  resources :posts do
    member do
      post 'upvote'
    end
  end

  resources :votes

  resources :images
   get 'imgur', to: 'images#imgur'

  root 'welcome#index'
  get '/about', to: 'welcome#about'

  delete 'users/:id/delete' => 'users#destroy'

  get '/all' => 'posts#all'

  get '/archive' => 'archive#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user && !current_user.profile
      redirect_to new_profile_path
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div id="home-wrapper">
  <div id="nav">
    <%= link_to "Contest", posts_path, class: "nav-contest" %><%= link_to "Winners Gallery", archive_path, class: "nav-contest" %>
    <% if current_user %>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-logout" %>
    <%= link_to "Your Profile", profile_path(current_user.id), class: "nav-profile" %>
    <% end %>
  </div>
  <div id="main-title">
    <h1>memr</h1>
  </div>
  <div class="description">
    <p>A Weekly Meme Contest. Post. Share. Win!</p>
  </div>
  <% if user_signed_in? %>
  <div id="button-style2" class="post-meme"><%= link_to "Enter Now!", new_post_path %></div>
  <% end %>
  <% if !current_user %>
  <div id="button-style" class="signup"><%= link_to "Sign Up", new_user_registration_path %></div>
  <div id="button-style" class="login"><%= link_to "Log In", new_user_session_path %></div>
  <div class="with-twitter"><i class="fa fa-twitter" aria-hidden="true"></i><%= link_to "Log In with Twitter", user_omniauth_authorize_path(:twitter) %></div>
  <% end %>
</div>