config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

  resources :profiles

  resources :posts do
    member do
      post 'upvote'
    end
  end

  resources :votes

  resources :images
   get 'imgur', to: 'images#imgur'

  root 'welcome#index'
  get '/about', to: 'welcome#about'

  delete 'users/:id/delete' => 'users#destroy'

  get '/all' => 'posts#all'

  get '/archive' => 'archive#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
include Magick

class Post < ActiveRecord::Base
  belongs_to :user
  has_many :votes
  has_one :meme
  has_one :archive


  has_attached_file :avatar, :styles =>
  { :medium => "400x400>", :thumb => "100x100>" },
  :default_url => "missing.png", id: "avatar"
  validates_attachment_content_type :avatar,
  content_type: /\Aimage\/.*\Z/

  validates :top_text, length: { maximum: 34 }
  validates :bottom_text, length: { maximum: 17 }


  MAX_LINE_CHARACTERS=17
  MAX_CHARACTERS=34


  def to_param
    "#{id}-#{user_id}"
  end

  # def last_week
  #   where(:created_at => (1.week.ago.beginning_of_week..1.week.ago.end_of_week)
  # end

  # def winner
  #   @post = Post.all.where(:created_at => (Time.zone.now.beginning_of_week..Time.zone.now.end_of_week))
  #   @winner = @post.votes.count.reverse.first(1)
  # end

  def top_line_meme(top)
    two_line_meme(top)
  end

  def bottom_line_meme(bottom)
    two_line_meme(nil, bottom)
  end

  def two_line_meme(top, bottom=nil)

    if (top.length > MAX_CHARACTERS || bottom.length > MAX_LINE_CHARACTERS)
      raise "Too many characters"
    end

    if (top.length > MAX_LINE_CHARACTERS)

      top_parts = top.split(' ')
      count = 0
      top_top = ""
      bottom_top = ""

      top_parts.each do |part|
        if count + (part.length + 1) < MAX_LINE_CHARACTERS
          top_top += " " + part
          count += part.length + 1
        else
          bottom_top += " " + part
        end
      end

      top = top_top + "\n" + bottom_top
    end

      img = Image.read(File.open(Meme.get_current_meme.avatar.path)).first

      caption = Draw.new

      caption.font = 'lib/assets/ufonts.com_impact.ttf'
      caption.fill = 'white'
      caption.pointsize = 50
      caption.font_weight = BoldWeight
      caption.stroke = 'black'
      caption.stroke_width = 3

      if (top)
        caption.annotate(img, 0,0,0,10, top.upcase) do
          self.gravity = NorthGravity
        end
      end

      if (bottom)
        caption.annotate(img, 0,0,0,10, bottom.upcase) do
          self.gravity = SouthGravity
        end
      end

      img.write(Rails.root + "public/memes/#{to_param}entry.jpg")

    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.all.where(:created_at => (Time.zone.now.beginning_of_week..Time.zone.now.end_of_week))
    @profile = Profile.where(user_id: params[:id]).first
  end

  def all
    @post = Post.all.where(:created_at => (Time.zone.now.beginning_of_week..Time.zone.now.end_of_week))
  end

  # def archive
  #   @post = Post.last_week.votes.count.reverse.first(1)
  # end

  def new
    @post = Post.new
    @current_image_url = Meme.get_current_meme.avatar.url(:medium)
    @max_top = Post.validators_on( :top_text ).first.options[:maximum]
    @max_bottom = Post.validators_on( :bottom_text ).first.options[:maximum]
  end

  def show
    @post = get_post
  end

  def edit
    @post = get_post
    @current_image_url = Meme.get_current_meme.avatar(:medium)
    @max_top = Post.validators_on( :top_text ).first.options[:maximum]
    @max_bottom = Post.validators_on( :bottom_text ).first.options[:maximum]
  end

  def create
    if current_user
      if Time.now.end_of_week > Time.now
        @post = Post.create(post_params)
        @post.two_line_meme(top_params[:top_text], bottom_params[:bottom_text])
        @post.avatar = File.open(Rails.root + "public/memes/#{@post.to_param}entry.jpg", "rb")
        if @post.save
          redirect_to post_path(@post.id)
        else
          flash[:alert] = "There was a problem"
          redirect_to 'posts/new'
        end
      end
    end
  end

  def update
    @post = get_post
    if current_user.id == @post.user_id
      @post.update(post_params)
        redirect_to post_path(params[:id]), notice: "Your meme was updated."
    else
        redirect_to root_path, alert: "Not your meme."
    end
  end

  def destroy
    @user = current_user
    @post = get_post
    @post.destroy
    redirect_to user_path(@user), notice: "Your entry was deleted."
  end

  def upvote
    # @vote = Vote.create(user_id: current_user.id, post_id: params[:post_id])
    @post = get_post
    if user_signed_in?
      @post.votes.create(user_id: current_user.id, post_id: params[:id])
    end
    if !user_signed_in?
      @post.votes.where(user_ip_address: request.remote_ip).empty?
      @post.votes.create(post_id: params[:id])
    end
    respond_to do |format|
      format.js
      format.html
    end
    # @vote = Vote.create(user_id: current_user.id, post_id: params[:post_id])
    # @post.votes.create
    # redirect_to post_path(params[:id])
  end

  private

  def get_post
    Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:top_text, :bottom_text, :avatar).merge(user_id: current_user.id)
  end

  def top_params
    params.require(:post).permit(:top_text).merge(user_id: current_user.id)
  end

  def bottom_params
    params.fetch(:post).permit(:bottom_text).merge(user_id: current_user.id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_votes.html.erb
<% post ||= @post %>
<div class="vote-info">
  <%= pluralize(post.votes.count, "Vote") %>
  <%= button_to upvote_post_path(post.id), method: :post, :id => "vote-button", remote: true do %>
    <i class="fa fa-plus-square fa-2x" aria-hidden="true"></i>
  <% end %>

</div>

app/views/posts/all.html.erb
<div id="nav">
  <%= link_to image_tag("logo-2.png", :class => "nav-home"), root_path %>
  <% if user_signed_in? %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-logout" %>
  <% end %>
</div>
<div id="contest-wrapper2">
  <h2>This Week's Submissions</h2>
  <div id="recent-meme">
    <% @post.each do |p| %>
    <%= image_tag p.avatar.url, :id => "meme-index" %>
    <div class="vote-info">
      <%= content_tag :div, class: "voting-partial #{p.id.to_s}" do %>
      <%= render partial: "posts/votes", locals: { post: p} %>
      <% end %>
      <p>by: <%= link_to p.user.profile.username, "/profiles/#{p.user_id}" %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div id="nav">
<%= link_to image_tag("logo-2.png", :class => "nav-home"), root_path %>
<% if user_signed_in? %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-logout" %>
  <%= link_to "Your Profile", profile_path(current_user.id), class: "nav-profile" %>
<% end %>
</div>

<div id="submit-meme">
  <h2>Update Your Meme</h2>
  <%= image_tag @current_image_url %>
   <%= form_for @post, :html => { :multipart => true } do |f| %>
   <%= f.label :top_text, "Top Text" %>
   <%= f.text_field :top_text, maxlength: @max_top, id: 'top_text' %><br>
   <p>Characters left: <span id="counter1" data-maximum-length="<%= @max_top %>"><%= @max_top %></span></p>
   <%= f.label :bottom_text, "Bottom Text" %>
   <%= f.text_field :bottom_text, maxlength: @max_bottom, id: 'bottom_text' %><br>
   <p>Characters left: <span id="counter2" data-maximum-length="<%= @max_bottom %>"><%= @max_bottom %></span></p>
   <%= f.submit :update, :class => "form-button" %>
   <% end %>
</div>

app/views/posts/index.html.erb
<div id="nav">
  <%= link_to image_tag("logo-2.png", :class => "nav-home"), root_path %>
  <% if user_signed_in? %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-logout" %>
  <%= link_to "Your Profile", profile_path(current_user.id), class: "nav-profile" %>
  <% end %>
</div>
<div id="contest-wrapper1">
  <i class="fa fa-history fa-3x" aria-hidden="true"></i><h2>Recent</h2>
  <div id="recent-meme">
    <% @post.reverse.first(8).each do |p| %>
    <%= image_tag p.avatar.url, :id => "meme-index" %>
    <div class="vote-info">
      <%= content_tag :div, class: "voting-partial #{p.id.to_s}" do %>
      <%= render partial: "posts/votes", locals: { post: p} %>
      <% end %>
      <p>by: <%= link_to p.user.profile.username, "/profiles/#{p.user_id}" %></p>
    </div>
    <% end %>
  </div>
  <div id="see"><%= link_to "See All", all_path, class: "see-all" %><p>&rarr;</p></div>
</div>
<div id="contest-wrapper2">
  <i class="fa fa-fire fa-3x" aria-hidden="true"></i><h2>Popular</h2>
  <div id="popular-meme">
    <% @post.sort_by { |post| post.votes.count }.reverse.first(8).each do |p| %>
    <%= image_tag p.avatar.url, :id => "meme-index" %>
    <div class="vote-info">
      <%= content_tag :div, class: "voting-partial #{p.id.to_s}" do %>
      <%= render partial: "posts/votes", locals: { post: p} %>
      <% end %>
      <p>by:  <%= link_to p.user.profile.username, "/profiles/#{p.user_id}" %></p>
    </div>
    <% end %>
  </div>
  <div id="see"><%= link_to "See All", all_path, class: "see-all" %><p>&rarr;</p></div>
</div>

app/views/posts/new.html.erb
<div id="nav">
<%= link_to image_tag("logo-2.png", :class => "nav-home"), root_path %>
<% if user_signed_in? %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-logout" %>
  <%= link_to "Your Profile", profile_path(current_user.id), class: "nav-profile" %>
<% end %>
</div>

<div id="submit-meme">
  <h2>Create Your Meme!</h2>
  <%= image_tag @current_image_url %>
   <%= form_for @post, :html => { :multipart => true } do |f| %>
   <%= f.label :top_text, "Top Text" %>
   <%= f.text_field :top_text, maxlength: @max_top, id: 'top_text' %><br>
   <p>Characters left: <span id="counter1" data-maximum-length="<%= @max_top %>"><%= @max_top %></span></p>
   <%= f.label :bottom_text, "Bottom Text" %>
   <%= f.text_field :bottom_text, maxlength: @max_bottom, id: 'bottom_text' %><br>
   <p>Characters left: <span id="counter2" data-maximum-length="<%= @max_bottom %>"><%= @max_bottom %></span></p>
   <%= f.submit :create, :class => "form-button" %>
   <% end %>
</div>

app/views/posts/show.html.erb
<div id="nav">
  <%= link_to image_tag("logo-2.png", :class => "nav-home"), root_path %>
  <% if user_signed_in? %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-logout" %>
  <% end %>
</div>
<div id="post-wrapper">
  <div id="single-post">
    <h2>Check This Meme Out!</h2>
    <%= image_tag "/memes/#{@post.id}-#{@post.user_id}entry.jpg", id: "meme-image" %>
    <div id="center">
    <div id="share-post">
      <% if current_user.id == @post.user_id %>
      <div id="dl-meme">
        <%= link_to "/memes/#{@post.id}-#{@post.user_id}entry.jpg", :download => 'yourmeme' do %>Download Your Meme<div class="fa fa-arrow-circle-down fa-2x dl-icon"></div><% end %>
        <% end %>
      </div>
      <div class="tweetbox">
        <a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out my meme and vote for me at Memr!" data-via="memrmemes">Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      </div>
      <% if @post.created_at <= Time.zone.now.end_of_week %>
      <%= content_tag :div, class: "voting-partial #{@post.id.to_s}" do %>
      <%= render 'votes'%>
      <% end %>
      <% end %>
      <div id="author">
        by: <%= link_to @post.user.profile.username, "/profiles/#{@post.user_id}" %>
      </div>
      <div id="change-post">
        <%= button_to 'Edit Post', edit_post_path(@post.id), method: :get, :class => "post-button" %>
        <%= button_to "Delete Post", "/posts/#{@post.id}", method: :delete, :class => "post-button2" %>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/posts/upvote.js.erb
$('.voting-partial.' + <%= @post.id.to_s %>).html("<%= j( render 'votes')%>")